In [7]:
import numpy as np #çalışmazsa !pip install numpy yaz

In [8]:
myList= [10,20,30,40]

In [9]:
my_array=np.array(myList)

In [10]:
my_array

array([10, 20, 30, 40])

In [11]:
type(my_array)


numpy.ndarray

In [12]:
int(my_array.max())

40

In [13]:
np.ones(5) #sadece birlerden oluşan dizi

array([1., 1., 1., 1., 1.])

In [14]:
np.zeros(5)#sadece sıfırlardan oluşan dizi

array([0., 0., 0., 0., 0.])

In [15]:
np.random.random_sample(5) #random sayılardan oluşan dizi

array([0.15917736, 0.82189422, 0.74504995, 0.75172422, 0.82805289])

***Array Aritmetic***

In [48]:
myList= [15,25]
myList2=[10,18]

In [49]:
myList+myList2 # 2 dizide de aynı sayıda değer olmalı ya da 1 tanesi tek elemanlı olmalı , 2 elemanlı diziyle 5 elemanlı dizi toplanmaz

[15, 25, 10, 18]

In [50]:
myArray1=np.array(myList)
myArray2=np.array(myList2)

In [51]:
myArray1+myArray2

array([25, 43])

In [52]:
myArray1 * 5

array([ 75, 125])

In [53]:
myArray1.max()

np.int64(25)

In [54]:
myArray1.min()

np.int64(15)

In [55]:
myArray1 .sum()

np.int64(40)

***Arange and İndex (liste ile aynıdır)***

In [61]:
liste= list(range(0,11,2))

In [62]:
liste

[0, 2, 4, 6, 8, 10]

In [63]:
np_array=np.arange(0,30,3)

In [64]:
np_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [66]:
np_array[0]

np.int64(0)

In [67]:
np_array[-1]

np.int64(27)

In [68]:
np_array[::-1]

array([27, 24, 21, 18, 15, 12,  9,  6,  3,  0])

In [69]:
np.random.randn(4)

array([-0.71842234, -0.55990453, -0.39499633, -0.97739487])

In [70]:
np.random.randn(4,4)

array([[ 0.61143581,  0.37827718, -0.38843489, -1.17170044],
       [-0.52161624,  0.05768181, -0.68253753,  0.32152482],
       [ 1.07309232, -1.37037259,  0.06496876,  1.7204904 ],
       [-0.01880956,  0.95315344, -1.82849306,  0.00456039]])

In [71]:
np.random.randint(0,300,5)

array([233, 174, 255, 147, 281], dtype=int32)